//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===================================
        ///INFO FROM PE32-FILES (IMPORT TABLE)
        ///===================================
        ///
        ///===================================
        ///===================================
        ///1
        ///kernel32.dll
        ///4258
        ///718
        ///200185
        ///14.14524%
        ///32.21900%
        ///===================================
        ///1 | 1
        ///GetLastError
        ///3314
        ///1.65547%
        ///0.53338%
        ///-----------------
        ///2 | 2
        ///CloseHandle
        ///3031
        ///1.51410%
        ///0.48783%
        ///-----------------
        ///3 | 3
        ///GetProcAddress
        ///2863
        ///1.43018%
        ///0.46079%
        ///-----------------
        ///4 | 4
        ///GetCurrentThreadId
        ///2756 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _01 {
            get {
                return ResourceManager.GetString("_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#MODULENAME#_IMPORT_INFORMATION:
        ///	.MODULE_NAME: 
        ///		
        ///		db &quot;#MODULENAME#&quot;, 0		
        ///		.str#FUNC#: db 0, 0, &quot;#FUNC#&quot;, 0
        ///       
        ///	    .FUNCTION_NAME_LIST:
        ///			dd .str#FUNC#
        ///            dd 0
        ///       
        ///	    .FUNCTION_ADDRESS_LIST:
        ///            dd .#FUNC#
        ///       
        ///	    .FUNCTION_ADDRESSES:
        ///			.#FUNC#:     dd 0.
        /// </summary>
        internal static string IMPORT_INFO_TEMPLATE {
            get {
                return ResourceManager.GetString("IMPORT_INFO_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #MODULENAME#_IMAGE_IMPORT_MODULE_DIRECTORY:
        /// .RVAFunctionNameList:   dd #MODULENAME#_IMPORT_INFORMATION.FUNCTION_NAME_LIST
        /// .Reserved1:     dd 0
        /// .Reserved2:      dd 0
        /// .RVAModuleName:     dd #MODULENAME#_IMPORT_INFORMATION.MODULE_NAME
        /// .RVAFunctionAddressList:  dd #MODULENAME#_IMPORT_INFORMATION.FUNCTION_ADDRESS_LIST.
        /// </summary>
        internal static string IMPORT_MODULE_TEMPLATE {
            get {
                return ResourceManager.GetString("IMPORT_MODULE_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %include &quot;include/global_constants.inc&quot;
        ///%include &quot;include/section_addresses.inc&quot;
        ///
        ///[ORG IDATA_SECTION_ADDRESS]
        ///
        ///#IMPORT_MODULE#
        ///
        ///TERMINATING_IMAGE_IMPORT_MODULE_DIRECTORY:
        /// .RVAFunctionNameList:   dd 0
        /// .Reserved1:     dd 0
        /// .Reserved2:      dd 0
        /// .RVAModuleName:     dd 0
        /// .RVAFunctionAddressList:  dd 0
        ///
        /// #IMPORT_INFO#.
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 VERSIONINFO
        ///FILEVERSION [FILEVERSION_COMMA]
        ///PRODUCTVERSION [PRODUCTVERSION_COMMA]
        ///FILEOS 0x4
        ///FILETYPE 0x1
        ///{
        ///BLOCK &quot;StringFileInfo&quot;
        ///{
        ///	BLOCK &quot;[HEX_32]&quot;
        ///	{		
        ///		VALUE &quot;FileDescription&quot;, &quot;[FILEDESCRIPTION]&quot;
        ///	}
        ///}
        ///
        ///BLOCK &quot;VarFileInfo&quot;
        ///{
        ///	VALUE &quot;Translation&quot;, [LANG] [CHARSET]
        ///}
        ///
        ///}
        ///.
        /// </summary>
        internal static string tmp {
            get {
                return ResourceManager.GetString("tmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 VERSIONINFO
        ///FILEVERSION [FILEVERSION_COMMA]
        ///PRODUCTVERSION [PRODUCTVERSION_COMMA]
        ///FILEOS 0x4
        ///FILETYPE 0x1
        ///{
        ///	BLOCK &quot;StringFileInfo&quot;
        ///	{
        ///		BLOCK &quot;[HEX_32]&quot;
        ///		{
        ///			VALUE &quot;CompanyName&quot;, &quot;[COMPANYNAME]&quot;
        ///			VALUE &quot;FileDescription&quot;, &quot;[FILEDESCRIPTION]&quot;
        ///			VALUE &quot;FileVersion&quot;, &quot;[FILEVERSION_COMMA]&quot;
        ///			VALUE &quot;InternalName&quot;, &quot;[INTERNALNAME]&quot;
        ///			VALUE &quot;LegalCopyright&quot;, &quot;[COPYRIGHT]&quot;
        ///			VALUE &quot;OriginalFilename&quot;, &quot;[ORIGFILENAME]&quot;
        ///			VALUE &quot;ProductName&quot;, &quot;[PRODUCTNAME]&quot;
        ///			VALUE &quot;ProductVersion&quot;, &quot;[PRO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string version_info {
            get {
                return ResourceManager.GetString("version_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;[FilePath]&quot; /va &quot;[FileVersion]&quot; /pv &quot;[ProductVersion]&quot; /s desc &quot;[Description]&quot; /s copyright &quot;[Copyright]&quot; /s company &quot;[Company]&quot; /s product &quot;[ProductName]&quot;.
        /// </summary>
        internal static string VPatcher {
            get {
                return ResourceManager.GetString("VPatcher", resourceCulture);
            }
        }
    }
}
